### ISSUE TITLE
Doesn't work if imported with ES6 style

### ISSUE THREAD

**Issue by rsetiawan7** [peterszombati/samp-node-lib#1]
My script not loaded properly if I use ES6 import style instead of CommonJS.

index.js
```javascript
import { OnGameModeInit } from 'samp-node-lib';

OnGameModeInit(() => console.log('Gamemode loaded from root index.js'));
```

But if you do:

```javascript
const { OnGameModeInit } = require('samp-node-lib');

OnGameModeInit(() => console.log('Gamemode loaded from root index.js'));
```

It would loaded correctly.

**Comment by peterszombati** [comment]
@rsetiawan7 
this import style only works in TypeScript

**Comment by cactyx** [comment]
> @rsetiawan7 this import style only works in TypeScript

That's not true. The import syntax technically has nothing to do with TypeScript. It's an [ECMAScript 2015 (ES6) language feature](https://262.ecma-international.org/6.0/#sec-imports) that was implemented by TypeScript early on, but has since become a native JavaScript feature.

Node.js started supporting the new ES6 modules [behind an experimental flag back in `8.9.0`](https://nodejs.medium.com/announcing-a-new-experimental-modules-1be8d2d6c2ff), and considered the implementation stable in version `12`.

At the time of creating this issue, the Node.js version used in the plugin was `10.19.1`, so ES6 modules were only supported with the flag `--experimental-modules` back then (which I can't seem to successfully set with the plugin's configuration). It's quite possible that OP didn't know about this and maybe something there is broken, too.

---

If you (the OP, or someone from the future stumbling over this issue) would like to use ES6 modules here, the newer versions of the plugin support it, you just have to set `"type": "module"` in the `package.json` file or use the `.mjs` file ending for your entry file to signal Node that you intend to [use ES6 modules](https://nodejs.org/api/packages.html#determining-module-system).
